app = "your-app-name"

[build]

[env]
PORT = "8000"

[[services]]
internal_port = 8000
protocol = "tcp"

[[services.ports]]
handlers = ["http", "tls"]
port = 80

[[services.ports]]
handlers = ["http", "tls"]
port = 443

[[services.ports]]
handlers = ["ws"]
port = 8000